#! /bin/bash

if [ $1 == "--help" ]; then
  echo "run the following:"
  echo "  brew update"
  echo "  brew upgrade"
  echo "  brew upgrade --cask"
else
  brew update
  brew upgrade
  brew upgrade --cask
fi