#! /bin/bash
if [ $1 == "--help" ]; then
  echo "explode <folder>"
  echo "explodes child folder into current folder"
  echo "Warning: unxpected behavior if files already exist in current folder"
else
  mv $1/* ./
  mv $1/.* ./  > /dev/null 2>&1 # will produce error about . and .. directories
  rmdir $1
fi
