name: johnhenry.github.io

on:
  pull_request:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install application
        run: npm install
      - name: Test test applicaiton
        run: npm test
