#! /bin/bash

# https://unix.stackexchange.com/questions/197792/joining-bash-arguments-into-single-string-with-spaces
read -p "$* (y/n)" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    exit 0
fi
exit 1